export type DestinationSuggestion = {
  value: string;
  keywords?: string[];
};

export const DESTINATION_SUGGESTIONS: DestinationSuggestion[] = [
  { value: "United States", keywords: ["usa", "us", "america", "united states"] },
  { value: "Boston, Massachusetts, USA", keywords: ["bos", "boston"] },
  { value: "Washington, DC, USA", keywords: ["washington dc", "dc", "dca", "iad"] },
  { value: "Philadelphia, Pennsylvania, USA", keywords: ["philadelphia", "philly", "phl"] },
  { value: "Orlando, Florida, USA", keywords: ["orlando", "mco"] },
  { value: "Tampa, Florida, USA", keywords: ["tampa", "tpa"] },
  { value: "New Orleans, Louisiana, USA", keywords: ["new orleans", "msy", "nola"] },
  { value: "Nashville, Tennessee, USA", keywords: ["nashville", "bna"] },
  { value: "Austin, Texas, USA", keywords: ["austin", "aus"] },
  { value: "Dallas, Texas, USA", keywords: ["dallas", "dfw", "dal"] },
  { value: "Houston, Texas, USA", keywords: ["houston", "iah", "hou"] },
  { value: "Denver, Colorado, USA", keywords: ["denver", "den"] },
  { value: "Phoenix, Arizona, USA", keywords: ["phoenix", "phx"] },
  { value: "San Diego, California, USA", keywords: ["san diego", "san", "san diego airport"] },
  { value: "Portland, Oregon, USA", keywords: ["portland", "pdx"] },
  { value: "Anchorage, Alaska, USA", keywords: ["anchorage", "anc", "alaska"] },
  { value: "Barcelona, Spain", keywords: ["barcelona", "bcn"] },
  { value: "Madrid, Spain", keywords: ["madrid", "mad"] },
  { value: "Seville, Spain", keywords: ["seville", "sevilla", "svq"] },
  { value: "Valencia, Spain", keywords: ["valencia", "vlc"] },
  { value: "Ibiza, Spain", keywords: ["ibiza", "ibi"] },
  { value: "Mallorca, Spain", keywords: ["mallorca", "palma", "pmi"] },
  { value: "Bordeaux, France", keywords: ["bordeaux", "bod"] },
  { value: "France", keywords: ["france"] },
  { value: "Paris, France", keywords: ["paris", "cdg", "ory"] },
  { value: "Nice, France", keywords: ["nice", "nce", "french riviera"] },
  { value: "Lyon, France", keywords: ["lyon", "lys"] },
  { value: "Provence, France", keywords: ["provence"] },
  { value: "French Riviera, France", keywords: ["french riviera", "cote d azur", "cannes", "monaco"] },
  { value: "Bologna, Italy", keywords: ["bologna", "blq"] },
  { value: "Italy", keywords: ["italy"] },
  { value: "Berlin, Germany", keywords: ["berlin", "ber"] },
  { value: "Germany", keywords: ["germany", "deutschland"] },
  { value: "Munich, Germany", keywords: ["munich", "muc"] },
  { value: "Hamburg, Germany", keywords: ["hamburg", "ham"] },
  { value: "Bangkok, Thailand", keywords: ["bangkok", "bkk"] },
  { value: "Thailand", keywords: ["thailand"] },
  { value: "Chiang Mai, Thailand", keywords: ["chiang mai", "cnx"] },
  { value: "Krabi, Thailand", keywords: ["krabi", "kbv"] },
  { value: "Koh Samui, Thailand", keywords: ["koh samui", "samui", "usm"] },
  { value: "Bali, Indonesia", keywords: ["bali", "dps"] },
  { value: "Indonesia", keywords: ["indonesia"] },
  { value: "Jakarta, Indonesia", keywords: ["jakarta", "cgk"] },
  { value: "Ubud, Bali, Indonesia", keywords: ["ubud"] },
  { value: "Budapest, Hungary", keywords: ["budapest", "bud"] },
  { value: "Brussels, Belgium", keywords: ["brussels", "bru"] },
  { value: "Buenos Aires, Argentina", keywords: ["buenos aires", "eze"] },
  { value: "Argentina", keywords: ["argentina"] },
  { value: "New York City, New York, USA", keywords: ["nyc", "new york", "jfk", "lga"] },
  { value: "Los Angeles, California, USA", keywords: ["los angeles", "la", "lax"] },
  { value: "San Francisco, California, USA", keywords: ["san francisco", "sf", "sfo"] },
  { value: "Chicago, Illinois, USA", keywords: ["chicago", "chi", "ord"] },
  { value: "Seattle, Washington, USA", keywords: ["seattle", "sea"] },
  { value: "Miami, Florida, USA", keywords: ["miami", "mia"] },
  { value: "Las Vegas, Nevada, USA", keywords: ["las vegas", "vegas", "las"] },
  { value: "Canada", keywords: ["canada"] },
  { value: "Toronto, Ontario, Canada", keywords: ["toronto", "yyz"] },
  { value: "Vancouver, British Columbia, Canada", keywords: ["vancouver", "yvr"] },
  { value: "Montreal, Quebec, Canada", keywords: ["montreal", "yul"] },
  { value: "Banff, Alberta, Canada", keywords: ["banff"] },
  { value: "Quebec City, Quebec, Canada", keywords: ["quebec city", "quebec"] },
  { value: "Mexico", keywords: ["mexico"] },
  { value: "London, England, UK", keywords: ["london", "lon", "lhr"] },
  { value: "United Kingdom", keywords: ["uk", "united kingdom", "britain", "great britain"] },
  { value: "Edinburgh, Scotland, UK", keywords: ["edinburgh", "edi"] },
  { value: "Manchester, England, UK", keywords: ["manchester", "man"] },
  { value: "Cotswolds, England, UK", keywords: ["cotswolds"] },
  { value: "Ireland", keywords: ["ireland"] },
  { value: "Rome, Italy", keywords: ["rome", "fco"] },
  { value: "Venice, Italy", keywords: ["venice", "vce"] },
  { value: "Florence, Italy", keywords: ["florence", "flr"] },
  { value: "Milan, Italy", keywords: ["milan", "mxp", "lin"] },
  { value: "Naples, Italy", keywords: ["naples", "nap"] },
  { value: "Amalfi Coast, Italy", keywords: ["amalfi", "amalfi coast", "positano", "ravello"] },
  { value: "Tuscany, Italy", keywords: ["tuscany"] },
  { value: "Sicily, Italy", keywords: ["sicily", "palermo", "catania"] },
  { value: "Sardinia, Italy", keywords: ["sardinia", "cagliari", "olbia"] },
  { value: "Lisbon, Portugal", keywords: ["lisbon", "lis"] },
  { value: "Porto, Portugal", keywords: ["porto", "opo"] },
  { value: "Portugal", keywords: ["portugal"] },
  { value: "Algarve, Portugal", keywords: ["algarve", "faro", "far"] },
  { value: "Madeira, Portugal", keywords: ["madeira", "funchal", "fnc"] },
  { value: "Spain", keywords: ["spain", "espana"] },
  { value: "Athens, Greece", keywords: ["athens", "ath"] },
  { value: "Santorini, Greece", keywords: ["santorini", "jtr"] },
  { value: "Greece", keywords: ["greece"] },
  { value: "Mykonos, Greece", keywords: ["mykonos", "jmk"] },
  { value: "Crete, Greece", keywords: ["crete", "heraklion", "her"] },
  { value: "Amsterdam, Netherlands", keywords: ["amsterdam", "ams"] },
  { value: "Netherlands", keywords: ["netherlands", "holland"] },
  { value: "Rotterdam, Netherlands", keywords: ["rotterdam"] },
  { value: "Prague, Czech Republic", keywords: ["prague", "prg"] },
  { value: "Czech Republic", keywords: ["czech republic", "czechia"] },
  { value: "Vienna, Austria", keywords: ["vienna", "vie"] },
  { value: "Austria", keywords: ["austria"] },
  { value: "Salzburg, Austria", keywords: ["salzburg", "szg"] },
  { value: "Zurich, Switzerland", keywords: ["zurich", "zrh"] },
  { value: "Switzerland", keywords: ["switzerland"] },
  { value: "Geneva, Switzerland", keywords: ["geneva", "gva"] },
  { value: "Interlaken, Switzerland", keywords: ["interlaken", "jungfrau"] },
  { value: "Reykjavik, Iceland", keywords: ["reykjavik", "kef"] },
  { value: "Iceland", keywords: ["iceland"] },
  { value: "South Coast, Iceland", keywords: ["south coast iceland"] },
  { value: "Dublin, Ireland", keywords: ["dublin", "dub"] },
  { value: "Croatia", keywords: ["croatia"] },
  { value: "Dubrovnik, Croatia", keywords: ["dubrovnik", "dbv"] },
  { value: "Split, Croatia", keywords: ["split", "spu"] },
  { value: "Hvar, Croatia", keywords: ["hvar"] },
  { value: "Turkey", keywords: ["turkey", "turkiye"] },
  { value: "Tokyo, Japan", keywords: ["tokyo", "hnd", "nrt"] },
  { value: "Kyoto, Japan", keywords: ["kyoto"] },
  { value: "Osaka, Japan", keywords: ["osaka", "kix"] },
  { value: "Japan", keywords: ["japan"] },
  { value: "Hokkaido, Japan", keywords: ["hokkaido", "cts", "sapporo"] },
  { value: "Sapporo, Japan", keywords: ["sapporo", "cts"] },
  { value: "Mount Fuji, Japan", keywords: ["mount fuji", "fuji", "fujikawaguchiko"] },
  { value: "Seoul, South Korea", keywords: ["seoul", "icn"] },
  { value: "South Korea", keywords: ["south korea", "korea"] },
  { value: "Busan, South Korea", keywords: ["busan", "pus"] },
  { value: "Jeju Island, South Korea", keywords: ["jeju", "jeju island", "cju"] },
  { value: "Singapore", keywords: ["singapore", "sin"] },
  { value: "Malaysia", keywords: ["malaysia"] },
  { value: "Kuala Lumpur, Malaysia", keywords: ["kuala lumpur", "kul", "kl"] },
  { value: "Penang, Malaysia", keywords: ["penang", "pen"] },
  { value: "Sydney, Australia", keywords: ["sydney", "syd"] },
  { value: "Melbourne, Australia", keywords: ["melbourne", "mel"] },
  { value: "Australia", keywords: ["australia"] },
  { value: "Brisbane, Australia", keywords: ["brisbane", "bne"] },
  { value: "Gold Coast, Australia", keywords: ["gold coast", "ool"] },
  { value: "Perth, Australia", keywords: ["perth", "per"] },
  { value: "Auckland, New Zealand", keywords: ["auckland", "akl"] },
  { value: "New Zealand", keywords: ["new zealand", "nz"] },
  { value: "Queenstown, New Zealand", keywords: ["queenstown", "zqn"] },
  { value: "Christchurch, New Zealand", keywords: ["christchurch", "chc"] },
  { value: "South Island, New Zealand", keywords: ["south island"] },
  { value: "Cape Town, South Africa", keywords: ["cape town", "cpt"] },
  { value: "South Africa", keywords: ["south africa"] },
  { value: "Johannesburg, South Africa", keywords: ["johannesburg", "jnb"] },
  { value: "Kruger National Park, South Africa", keywords: ["kruger", "kruger national park"] },
  { value: "Marrakesh, Morocco", keywords: ["marrakesh", "rak", "marrakech"] },
  { value: "Morocco", keywords: ["morocco"] },
  { value: "Casablanca, Morocco", keywords: ["casablanca", "cmn"] },
  { value: "Fes, Morocco", keywords: ["fes", "fez"] },
  { value: "Sahara Desert, Morocco", keywords: ["sahara", "merzouga"] },
  { value: "Dubai, United Arab Emirates", keywords: ["dubai", "dxb"] },
  { value: "Abu Dhabi, United Arab Emirates", keywords: ["abu dhabi", "auh"] },
  { value: "United Arab Emirates", keywords: ["uae", "united arab emirates"] },
  { value: "Istanbul, Turkiye", keywords: ["istanbul", "ist"] },
  { value: "Cappadocia, Turkiye", keywords: ["cappadocia", "nevsehir"] },
  { value: "Cairo, Egypt", keywords: ["cairo", "cai"] },
  { value: "Egypt", keywords: ["egypt"] },
  { value: "Luxor, Egypt", keywords: ["luxor", "lxr"] },
  { value: "Mexico City, Mexico", keywords: ["mexico city", "mex", "cdmx"] },
  { value: "Cancun, Mexico", keywords: ["cancun", "cun"] },
  { value: "Tulum, Mexico", keywords: ["tulum"] },
  { value: "Oaxaca, Mexico", keywords: ["oaxaca", "oax"] },
  { value: "Lima, Peru", keywords: ["lima", "lim"] },
  { value: "Cusco, Peru", keywords: ["cusco", "cuz"] },
  { value: "Peru", keywords: ["peru"] },
  { value: "Machu Picchu, Peru", keywords: ["machu picchu"] },
  { value: "Sacred Valley, Peru", keywords: ["sacred valley"] },
  { value: "Rio de Janeiro, Brazil", keywords: ["rio", "gig"] },
  { value: "Brazil", keywords: ["brazil", "brasil"] },
  { value: "Sao Paulo, Brazil", keywords: ["sao paulo", "gru", "cgh"] },
  { value: "Salvador, Brazil", keywords: ["salvador"] },
  { value: "San Jose, Costa Rica", keywords: ["san jose", "sjo"] },
  { value: "Costa Rica", keywords: ["costa rica"] },
  { value: "La Fortuna, Costa Rica", keywords: ["la fortuna", "arenal"] },
  { value: "Manuel Antonio, Costa Rica", keywords: ["manuel antonio"] },
  { value: "Honolulu, Hawaii, USA", keywords: ["honolulu", "hnl", "oahu"] },
  { value: "Maui, Hawaii, USA", keywords: ["maui", "kahului"] },
  { value: "Kauai, Hawaii, USA", keywords: ["kauai", "lihue", "lih"] },
  { value: "Phuket, Thailand", keywords: ["phuket", "hkt"] },
  { value: "Hanoi, Vietnam", keywords: ["hanoi", "han"] },
  { value: "Ho Chi Minh City, Vietnam", keywords: ["ho chi minh", "saigon", "sgn"] },
  { value: "Vietnam", keywords: ["vietnam"] },
  { value: "Da Nang, Vietnam", keywords: ["da nang", "dad"] },
  { value: "Hoi An, Vietnam", keywords: ["hoi an"] },
  { value: "Ha Long Bay, Vietnam", keywords: ["ha long bay", "halong"] },
  { value: "Philippines", keywords: ["philippines"] },
  { value: "Manila, Philippines", keywords: ["manila", "mnl"] },
  { value: "Cebu, Philippines", keywords: ["cebu", "ceb"] },
  { value: "Palawan, Philippines", keywords: ["palawan", "el nido", "puerto princesa"] },
  { value: "Boracay, Philippines", keywords: ["boracay", "mph"] },
  { value: "Sri Lanka", keywords: ["sri lanka"] },
  { value: "Colombo, Sri Lanka", keywords: ["colombo", "cmb"] },
  { value: "Ella, Sri Lanka", keywords: ["ella"] },
  { value: "Galle, Sri Lanka", keywords: ["galle"] },
  { value: "India", keywords: ["india"] },
  { value: "Delhi, India", keywords: ["delhi", "del", "new delhi"] },
  { value: "Mumbai, India", keywords: ["mumbai", "bom"] },
  { value: "Jaipur, India", keywords: ["jaipur"] },
  { value: "Goa, India", keywords: ["goa"] },
  { value: "Agra, India", keywords: ["agra", "taj mahal"] },
  { value: "China", keywords: ["china"] },
  { value: "Beijing, China", keywords: ["beijing", "pek"] },
  { value: "Shanghai, China", keywords: ["shanghai", "pvg"] },
  { value: "Hong Kong", keywords: ["hong kong", "hkg"] },
  { value: "Taipei, Taiwan", keywords: ["taipei", "tpe", "taiwan"] },
  { value: "Norway", keywords: ["norway"] },
  { value: "Oslo, Norway", keywords: ["oslo", "osl"] },
  { value: "Bergen, Norway", keywords: ["bergen", "bgo"] },
  { value: "Norwegian Fjords, Norway", keywords: ["fjords", "norwegian fjords", "geiranger"] },
  { value: "Sweden", keywords: ["sweden"] },
  { value: "Stockholm, Sweden", keywords: ["stockholm", "arn"] },
  { value: "Denmark", keywords: ["denmark"] },
  { value: "Copenhagen, Denmark", keywords: ["copenhagen", "cph"] },
  { value: "Finland", keywords: ["finland"] },
  { value: "Helsinki, Finland", keywords: ["helsinki", "hel"] },
  { value: "Lapland, Finland", keywords: ["lapland", "rovaniemi", "rvn"] },
  { value: "Poland", keywords: ["poland"] },
  { value: "Krakow, Poland", keywords: ["krakow", "krk"] },
  { value: "Warsaw, Poland", keywords: ["warsaw", "waw"] },
  { value: "Slovenia", keywords: ["slovenia"] },
  { value: "Ljubljana, Slovenia", keywords: ["ljubljana", "lju"] },
  { value: "Lake Bled, Slovenia", keywords: ["lake bled", "bled"] },
  { value: "Czechia", keywords: ["czechia"] },
  { value: "Belgium", keywords: ["belgium"] },
  { value: "Bruges, Belgium", keywords: ["bruges", "brugge"] },
  { value: "Antwerp, Belgium", keywords: ["antwerp"] },
  { value: "Hungary", keywords: ["hungary"] },
  { value: "Japan Alps, Japan", keywords: ["japan alps"] },
  { value: "Patagonia, Argentina", keywords: ["patagonia"] },
  { value: "Zanzibar, Tanzania", keywords: ["zanzibar"] },
  { value: "Tanzania", keywords: ["tanzania"] },
  { value: "Serengeti, Tanzania", keywords: ["serengeti"] },
  { value: "Kenya", keywords: ["kenya"] },
  { value: "Nairobi, Kenya", keywords: ["nairobi", "nbo"] },
  { value: "Masai Mara, Kenya", keywords: ["masai mara", "maasai mara"] },
  { value: "Botswana", keywords: ["botswana"] },
  { value: "Okavango Delta, Botswana", keywords: ["okavango", "okavango delta"] },
];

function matchesWordStart(query: string, candidate: string) {
  return candidate
    .toLowerCase()
    .split(/[\s,/-]+/)
    .some((word) => word.startsWith(query));
}

export function filterDestinationSuggestions(query: string, limit = 8): DestinationSuggestion[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [];

  return DESTINATION_SUGGESTIONS.filter((suggestion) => {
    if (suggestion.value.toLowerCase().startsWith(normalized)) return true;
    if (matchesWordStart(normalized, suggestion.value)) return true;
    return suggestion.keywords?.some((keyword) => keyword.toLowerCase().startsWith(normalized)) ?? false;
  }).slice(0, limit);
}
